### ISSUE TITLE
Support for Component / yPbPr

### ISSUE THREAD

**Issue by adamlwgriffiths** [AKuHAK/Fceumm-PS2#1]
When running with component cables, FCEU will insist on outputting Composite video, which results in an `Invalid Format` dialog from my TV.
I've tried all of the FCEU releases for PS2 that I can find (90i, mm, etc) and found that none work with component.
It seems that only InfoNES supports component video out (yPbPr). However, InfoNES isn't functionally complete, nor up to the standard of FCEU. So I would like to use FCEU if possible.

This same issue exists for snes9x, where only Snes Station is able to output to component.

I'm not intending to "advertise", but if you don't have a component cable to test you can get one pretty cheaply on aliexpress. Otherwise, ebay will have them.

**Comment by AKuHAK** [comment]
MMM why you cannot just load it via GSM selector? In last release I fixed issue when you cannot launch it with GSM with proper video. The only thing you cannot change videomode inside emulator :)

**Comment by adamlwgriffiths** [comment]
Sorry for the delay. I haven't abandoned this issue, I just haven't had a chance to go near my PS2 for a while.

I failed to mention the version I'm using: FCEU 0.93.

I haven't used GSM and will have to take a look.

Are you saying that using GSM is the only way to get FCEU to work with component video?
Is is possible to investigate getting FCEU working without GSM?
Other PS2 games work fine - although I haven't tried running any from the HD.

**Comment by AKuHAK** [comment]
Yes it is the only way not only for this emulator but almost for every old homebrew to get working with progressive scan. It is possible to make such a thing inside emulator but it need heavy modifications and probably I will not do it.

Just try [GDM](http://ps2home.freeforums.net/thread/268/mode-selector-gsm-development-guides)

**Comment by adamlwgriffiths** [comment]
Interesting, thanks for the help. I'll try out GSM.

Out of curiosity, I would have thought handling higher resolutions would simply be a larger framebuffer.
Or are you saying that the emulator makes assumptions about the framebuffer size and to change this would require changing this assumption throughout the code base?
Is there any code you could point me to, to show me where this is an issue?

**Comment by adamlwgriffiths** [comment]
Ok sorry, 'progressive' means non-interlaced, I wasn't aware of that.
So it seems that FCEU is built around the assumption that output is always interlaced?

I'd be curious to see some examples in the code of where this is.

**Comment by AKuHAK** [comment]
It has 4 video modes: pal interlaced, ntsc interlaced (standard ps2 video modes)
and 2 modes: pal non-interlaced and ntsc non-interlaced (aka progressive modes also called 240p modes)
https://github.com/AKuHAK/Fceumm-PS2/blob/master/src/drivers/ps2/init.c
This 2 are native video modes for old consoles such a psone or NES.

But if you want to use 480p (which is also progressive) or 1080i you need to use gsm. I didnt implement this cause you didnt see better picture.

**Comment by adamlwgriffiths** [comment]
Awesome, thanks for taking the time to explain, much appreciated.
